dist: bionic

os:
  - linux
  - osx

language: c

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
      - valgrind
      - lcov
      - libprotobuf-c-dev
      - protobuf-c-compiler
    update: true
  homebrew:
    packages:
      - valgrind
      - lcov
      - protobuf-c

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip install cpp-coveralls ; fi

script:
    - ./autogen.sh
    - ./configure && make -j2 distcheck VERBOSE=1 && make clean
    - ./configure --enable-valgrind-tests && make -j2 distcheck DISTCHECK_CONFIGURE_FLAGS="--enable-valgrind-tests" VERBOSE=1 && make clean
    - if [ "$CC" = "gcc" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then ./configure --enable-code-coverage && make -j2 && make check; fi

after_success:
    - if [ "$CC" = "gcc" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then cpp-coveralls --build-root . --exclude t/ --exclude /usr/include --exclude example; fi
