/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eso_cpl_jni_LibraryLoader */

#ifndef _Included_org_eso_cpl_jni_LibraryLoader
#define _Included_org_eso_cpl_jni_LibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eso_cpl_jni_LibraryLoader
 * Method:    nativeLTDLInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eso_cpl_jni_LibraryLoader_nativeLTDLInit
  (JNIEnv *, jclass);

/*
 * Class:     org_eso_cpl_jni_LibraryLoader
 * Method:    nativeLTDLExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eso_cpl_jni_LibraryLoader_nativeLTDLExit
  (JNIEnv *, jclass);

/*
 * Class:     org_eso_cpl_jni_LibraryLoader
 * Method:    nativeMakeLibrary
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/eso/cpl/jni/PluginLibrary;
 */
JNIEXPORT jobject JNICALL Java_org_eso_cpl_jni_LibraryLoader_nativeMakeLibrary
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
