/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eso_cpl_jni_PluginLibrary */

#ifndef _Included_org_eso_cpl_jni_PluginLibrary
#define _Included_org_eso_cpl_jni_PluginLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eso_cpl_jni_PluginLibrary
 * Method:    nativeUnload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eso_cpl_jni_PluginLibrary_nativeUnload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
