/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eso_cpl_jni_CPLControl */

#ifndef _Included_org_eso_cpl_jni_CPLControl
#define _Included_org_eso_cpl_jni_CPLControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eso_cpl_jni_CPLControl
 * Method:    nativeEnsureSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eso_cpl_jni_CPLControl_nativeEnsureSetup
  (JNIEnv *, jclass);

/*
 * Class:     org_eso_cpl_jni_CPLControl
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eso_cpl_jni_CPLControl_nativeGetVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
