/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eso_cpl_jni_JNIParameterImp */

#ifndef _Included_org_eso_cpl_jni_JNIParameterImp
#define _Included_org_eso_cpl_jni_JNIParameterImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eso_cpl_jni_JNIParameterImp
 * Method:    nativeSetValue
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_eso_cpl_jni_JNIParameterImp_nativeSetValue
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
