/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eso_cpl_jni_JNIRecipe */

#ifndef _Included_org_eso_cpl_jni_JNIRecipe
#define _Included_org_eso_cpl_jni_JNIRecipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eso_cpl_jni_JNIRecipe
 * Method:    nativeInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_eso_cpl_jni_JNIRecipe_nativeInitialize
  (JNIEnv *, jobject);

/*
 * Class:     org_eso_cpl_jni_JNIRecipe
 * Method:    nativeDeinitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_eso_cpl_jni_JNIRecipe_nativeDeinitialize
  (JNIEnv *, jobject);

/*
 * Class:     org_eso_cpl_jni_JNIRecipe
 * Method:    nativeExecute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_eso_cpl_jni_JNIRecipe_nativeExecute
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_eso_cpl_jni_JNIRecipe
 * Method:    nativeGetParameterArray
 * Signature: ()[Lorg/eso/cpl/Parameter;
 */
JNIEXPORT jobjectArray JNICALL Java_org_eso_cpl_jni_JNIRecipe_nativeGetParameterArray
  (JNIEnv *, jobject);

/*
 * Class:     org_eso_cpl_jni_JNIRecipe
 * Method:    nativeGetFrameArray
 * Signature: ()[Lorg/eso/cpl/Frame;
 */
JNIEXPORT jobjectArray JNICALL Java_org_eso_cpl_jni_JNIRecipe_nativeGetFrameArray
  (JNIEnv *, jobject);

/*
 * Class:     org_eso_cpl_jni_JNIRecipe
 * Method:    nativeSetFrameArray
 * Signature: ([Lorg/eso/cpl/Frame;)V
 */
JNIEXPORT void JNICALL Java_org_eso_cpl_jni_JNIRecipe_nativeSetFrameArray
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
