# CMake generated Testfile for 
# Source directory: E:/workspace/funra/source/3rd/cmocka/tests
# Build directory: E:/workspace/funra/proj/vs2017/3rd/cmocka/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_alloc "test_alloc")
set_tests_properties(test_alloc PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_group_setup_assert "test_group_setup_assert")
set_tests_properties(test_group_setup_assert PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" WILL_FAIL "1")
add_test(test_group_setup_fail "test_group_setup_fail")
set_tests_properties(test_group_setup_fail PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" WILL_FAIL "1")
add_test(test_fixtures "test_fixtures")
set_tests_properties(test_fixtures PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_group_fixtures "test_group_fixtures")
set_tests_properties(test_group_fixtures PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_groups "test_groups")
set_tests_properties(test_groups PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_float_macros "test_float_macros")
set_tests_properties(test_float_macros PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_double_macros "test_double_macros")
set_tests_properties(test_double_macros PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_assert_macros "test_assert_macros")
set_tests_properties(test_assert_macros PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_assert_macros_fail "test_assert_macros_fail")
set_tests_properties(test_assert_macros_fail PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  FAILED  \\] tests: 1 test")
add_test(test_basics "test_basics")
set_tests_properties(test_basics PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_skip "test_skip")
set_tests_properties(test_skip PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  SKIPPED \\] test_check_skip")
add_test(test_strmatch "test_strmatch")
set_tests_properties(test_strmatch PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_setup_fail "test_setup_fail")
set_tests_properties(test_setup_fail PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" WILL_FAIL "1")
add_test(test_ordering "test_ordering")
set_tests_properties(test_ordering PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_ordering_fail "test_ordering_fail")
set_tests_properties(test_ordering_fail PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  FAILED  \\] tests: 7 test")
add_test(test_returns "test_returns")
set_tests_properties(test_returns PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_returns_fail "test_returns_fail")
set_tests_properties(test_returns_fail PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  FAILED  \\] alloc_tests: 3 test")
add_test(test_string "test_string")
set_tests_properties(test_string PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_wildcard "test_wildcard")
set_tests_properties(test_wildcard PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_skip_filter "test_skip_filter")
set_tests_properties(test_skip_filter PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(test_exception_handler "test_exception_handler")
set_tests_properties(test_exception_handler PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "EXCEPTION_ACCESS_VIOLATION occurred at")
add_test(test_setup_fail_1_failed "test_setup_fail")
set_tests_properties(test_setup_fail_1_failed PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  ERROR   \\] int_test_ignored")
add_test(test_setup_fail_1_passed "test_setup_fail")
set_tests_properties(test_setup_fail_1_passed PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  PASSED  \\] 1 test\\(s\\).")
add_test(test_setup_fail_match_failed "test_setup_fail")
set_tests_properties(test_setup_fail_match_failed PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[  ERROR   \\] int_test_ignored")
add_test(test_setup_fail_match_passed "test_setup_fail")
set_tests_properties(test_setup_fail_match_passed PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" PASS_REGULAR_EXPRESSION "\\[       OK \\] int_test_success")
add_test(test_basics_tap "test_basics")
set_tests_properties(test_basics_tap PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=tap" PASS_REGULAR_EXPRESSION "^TAP version 13[ 
]+1\\.\\.2[ 
]+ok 1 - null_test_success[ 
]+ok 2 - int_test_success[ 
]+# ok - tests")
add_test(test_assert_macros_fail_tap "test_assert_macros_fail")
set_tests_properties(test_assert_macros_fail_tap PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=tap" PASS_REGULAR_EXPRESSION "^TAP version 13[ 
]+1\\.\\.1[ 
]+not ok 1 - test_assert_return_code_fail[ 
]+#[^
]+[
]#[^
]+[
]# not ok - tests")
add_test(test_groups_tap "test_groups")
set_tests_properties(test_groups_tap PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=tap" PASS_REGULAR_EXPRESSION "^TAP version 13[ 
]+1\\.\\.1[ 
]+ok 1 - null_test_success[ 
]+# ok - test_group1[ 
]+1\\.\\.1[ 
]+ok 1 - int_test_success[ 
]+# ok - test_group2")
add_test(test_skip_tap "test_skip")
set_tests_properties(test_skip_tap PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=tap" PASS_REGULAR_EXPRESSION "ok 1 # SKIP")
add_test(test_setup_fail_tap "test_setup_fail")
set_tests_properties(test_setup_fail_tap PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=tap" PASS_REGULAR_EXPRESSION "not ok 1 - int_test_ignored Could not run test: Test setup failed")
add_test(test_basics_subunit "test_basics")
set_tests_properties(test_basics_subunit PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=subunit" PASS_REGULAR_EXPRESSION "^test: null_test_success[ 
]+success: null_test_success")
add_test(test_assert_macros_fail_subunit "test_assert_macros_fail")
set_tests_properties(test_assert_macros_fail_subunit PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=subunit" PASS_REGULAR_EXPRESSION "failure: test_assert_return_code_fail \\[")
add_test(test_groups_subunit "test_groups")
set_tests_properties(test_groups_subunit PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=subunit" PASS_REGULAR_EXPRESSION "^test: null_test_success[ 
]+success: null_test_success")
add_test(test_skip_subunit "test_skip")
set_tests_properties(test_skip_subunit PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=subunit" PASS_REGULAR_EXPRESSION "^test: test_check_skip[ 
]+skip: test_check_skip")
add_test(test_setup_fail_subunit "test_setup_fail")
set_tests_properties(test_setup_fail_subunit PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=subunit" PASS_REGULAR_EXPRESSION "error: int_test_ignored \\[ Could not run test: Test setup failed \\]")
add_test(test_basics_xml "test_basics")
set_tests_properties(test_basics_xml PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=xml" PASS_REGULAR_EXPRESSION "<testsuite name=\"tests\" time=\"[0-9.]+\" tests=\"2\" failures=\"0\" errors=\"0\" skipped=\"0\" >[ 
]+<testcase name=\"null_test_success\" time=\"[0-9.]+\" >.*</testcase>")
add_test(test_assert_macros_fail_xml "test_assert_macros_fail")
set_tests_properties(test_assert_macros_fail_xml PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=xml" PASS_REGULAR_EXPRESSION "<testcase name=\"test_assert_return_code_fail\" time=\"[0-9.]+\" >[ 
]+<failure>")
add_test(test_groups_xml "test_groups")
set_tests_properties(test_groups_xml PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=xml" PASS_REGULAR_EXPRESSION "^<\\?xml version=\"1.0\" encoding=\"UTF-8\" \\?>[ 
]+<testsuites>[ 
]+<testsuite name=\"test_group1\" time=\"[0-9.]+\" tests=\"1\" failures=\"0\" errors=\"0\" skipped=\"0\" >[ 
]+<testcase name=\"null_test_success\" time=\"[0-9.]+\" >[ 
]+</testcase>[ 
]+</testsuite>[ 
]+.*<testsuite name=\"test_group2\" time=\"[0-9.]+\" tests=\"1\" failures=\"0\" errors=\"0\" skipped=\"0\" >[ 
]+<testcase name=\"int_test_success\" time=\"[0-9.]+\" >[ 
]+</testcase>[ 
]+</testsuite>[ 
]+</testsuites>")
add_test(test_skip_xml "test_skip")
set_tests_properties(test_skip_xml PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=xml" PASS_REGULAR_EXPRESSION "<testcase name=\"test_check_skip\" time=\"[0-9.]+\" >[ 
]+<skipped/>")
add_test(test_setup_fail_xml "test_setup_fail")
set_tests_properties(test_setup_fail_xml PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;;CMOCKA_MESSAGE_OUTPUT=xml" PASS_REGULAR_EXPRESSION "<testcase name=\"int_test_ignored\" time=\"[0-9.]+\" >[ 
]+<failure><!\\[CDATA\\[Test setup failed\\]\\]></failure>")
