# CMake generated Testfile for 
# Source directory: E:/workspace/funra/source/3rd/cmocka/example
# Build directory: E:/workspace/funra/proj/vs2017/3rd/cmocka/example
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(simple_test "simple_test")
set_tests_properties(simple_test PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;")
add_test(allocate_module_test "allocate_module_test")
set_tests_properties(allocate_module_test PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" WILL_FAIL "1")
add_test(assert_macro_test "assert_macro_test")
set_tests_properties(assert_macro_test PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" WILL_FAIL "1")
add_test(assert_module_test "assert_module_test")
set_tests_properties(assert_module_test PROPERTIES  ENVIRONMENT "PATH=E:\\workspace\\funra\\proj\\vs2017\\3rd\\cmocka\\src\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\IDM Computer Solutions\\UltraEdit\\;E:\\tools\\msys64——\\;E:\\tools\\android-ndk-r10e-windows-x86_64——\\;E:\\tools\\MinGW——\\x64\\bin\\;E:\\tools\\MinGW——\\x86\\bin\\;C:\\Program Files\\Android\\jdk\\microsoft_dist_openjdk_1.8.0.25\\bin\\;D:\\ENV\\tomcat7\\bin\\;%MSBuild_Home%\\;%Dotnet_Home%\\;D:\\tools\\Git\\bin\\\\;%Python_Home%\\;%Python_Home%\\Scripts\\;D:\\tools\\CMake\\bin\\;E:\\ENV\\MicrosoftVSCode\\bin\\;D:\\workspace\\abyss\\trunk\\Client\\Tools\\svn\\;C:\\Program Files\\dotnet\\\\;E:\\tools\\msys64\\mingw64\\bin\\;D:\\ENV\\sqlite3\\\\;F:\\tools\\TortoiseSVN\\bin\\;C:\\Users\\Ray\\AppData\\Local\\Microsoft\\WindowsApps\\python\\;C:\\Users\\Ray\\.dotnet\\tools\\;E:\\ENV\\MicrosoftVSCode\\bin\\;C:\\Users\\Ray\\.dotnet\\tools\\;" WILL_FAIL "1")
